version: '3.9'

services:
  app:
    build:
      context: .
    command: sh -c "composer install && php artisan serve --host 0.0.0.0 "
    working_dir: /vol/www
    volumes:
      - ./laravel-app:/vol/www
      - .env:/vol/www/.env
    ports:
      - "8000:8000"
